[package]
name = "komadori"
version = "0.1.0"
authors = ["Wobscale Authors"]

[dependencies]
log = "*"
env_logger = "*"
rocket = "0.3.3"
serde_json = "*"
rocket_codegen = "0.3.3"
diesel = { version = "0.16.0", features = ["postgres"] }
diesel_codegen = { version = "0.16.0", features = ["postgres"] }
r2d2 = "*"
r2d2-diesel = "*"
