# Please note, this docker-compose file is meant
# *ONLY* for development purposes and is not a good basis for a production
# deployment.

version: '3'

networks:
  default: {}
  internal:
    internal: true
services:
  db:
    image: postgres
    env_file: ./hack/compose/db_env
    volumes:
    - "./hack/compose/db-init.sh:/docker-entrypoint-initdb.d/db-init.sh"
    network_mode: "service:hydra"
  hydra:
    image: oryd/hydra:v0.11.12-alpine
    env_file: ./hack/compose/hydra_env
    entrypoint: /hack/compose/hydra-init.sh
    command: host --dangerous-force-http
    volumes:
    - "./hack:/hack"
    networks:
    - default
    extra_hosts:
    - "db:127.0.0.1"
